[project]
name = "deepresearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cerebras-cloud-sdk>=1.50.1",
    "fastapi>=0.118.0",
    "linkup-sdk>=0.6.0",
    "python-dotenv>=1.1.1",
]
